export {cssProperties}

const cssProperties = {
  alignContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'stretch'],
  alignItems: ['flex-start', 'flex-end', 'center', 'baseline', 'stretch'],
  alignSelf: ['auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch'],
  animation: ['animation-name', 'animation-duration', 'animation-timing-function', 'animation-delay', 'animation-iteration-count', 'animation-direction', 'animation-fill-mode', 'animation-play-state'],
  animationDelay: ['0s', '1s', '2s', '3s', '4s', '5s'],
  animationDirection: ['normal', 'reverse', 'alternate', 'alternate-reverse'],
  animationDuration: ['0s', '1s', '2s', '3s', '4s', '5s'],
  animationFillMode: ['none', 'forwards', 'backwards', 'both'],
  animationIterationCount: ['infinite', '1', '2', '3', '4', '5'],
  animationName: ['none', 'slidein', 'fadein', 'rotate'],
  animationPlayState: ['running', 'paused'],
  animationTimingFunction: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
  backfaceVisibility: ['visible', 'hidden'],
  background: ['color', 'image', 'position', 'size', 'repeat', 'attachment', 'origin', 'clip'],
  backgroundAttachment: ['scroll', 'fixed', 'local'],
  backgroundBlendMode: ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity'],
  backgroundClip: ['border-box', 'padding-box', 'content-box', 'text'],
  backgroundColor: ['color', 'transparent'],
  backgroundImage: ['url', 'none'],
  backgroundOrigin: ['padding-box', 'border-box', 'content-box'],
  backgroundPosition: ['center', 'top', 'right', 'bottom', 'left', 'x% y%', 'xpos ypos', 'center center'],
  backgroundRepeat: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
  backgroundSize: ['auto', 'contain', 'contain'],
  blockSize: ['auto', 'length', 'percentage'],
  border: ['border-width', 'border-style', 'border-color'],
  borderBlock: ['border-block-width', 'border-block-style', 'border-block-color'],
  borderBlockColor: ['color', 'transparent'],
  borderBlockEnd: ['border-block-end-width', 'border-block-end-style', 'border-block-end-color'],
  borderBlockEndColor: ['color', 'transparent'],
  borderBlockEndStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderBlockEndWidth: ['thin', 'medium', 'thick', 'length'],
  borderBlockStart: ['border-block-start-width', 'border-block-start-style', 'border-block-start-color'],
  borderBlockStartColor: ['color', 'transparent'],
  borderBlockStartStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderBlockStartWidth: ['thin', 'medium', 'thick', 'length'],
  borderBottom: ['border-bottom-width', 'border-bottom-style', 'border-bottom-color'],
  borderBottomColor: ['color', 'transparent'],
  borderBottomLeftRadius: ['length', 'percentage'],
  borderBottomRightRadius: ['length', 'percentage'],
  borderBottomStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderBottomWidth: ['thin', 'medium', 'thick', 'length'],
  borderCollapse: ['collapse', 'separate'],
  borderColor: ['color', 'transparent'],
  borderImage: ['border-image-source', 'border-image-slice', 'border-image-width', 'border-image-outset', 'border-image-repeat'],
  borderImageOutset: ['length', 'number'],
  borderImageRepeat: ['stretch', 'repeat', 'round', 'space'],
  borderImageSlice: ['number', 'percentage', 'fill'],
  borderImageSource: ['url', 'none'],
  borderImageWidth: ['length', 'percentage', 'auto'],
  borderInline: ['border-inline-width', 'border-inline-style', 'border-inline-color'],
  borderInlineColor: ['color', 'transparent'],
  borderInlineEnd: ['border-inline-end-width', 'border-inline-end-style', 'border-inline-end-color'],
  borderInlineEndColor: ['color', 'transparent'],
  borderInlineEndStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderInlineEndWidth: ['thin', 'medium', 'thick', 'length'],
  borderInlineStart: ['border-inline-start-width', 'border-inline-start-style', 'border-inline-start-color'],
  borderInlineStartColor: ['color', 'transparent'],
  borderInlineStartStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderInlineStartWidth: ['thin', 'medium', 'thick', 'length'],
  borderLeft: ['border-left-width', 'border-left-style', 'border-left-color'],
  borderLeftColor: ['color', 'transparent'],
  borderLeftStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderLeftWidth: ['thin', 'medium', 'thick', 'length'],
  borderRadius: ['length', 'percentage'],
  borderRight: ['border-right-width', 'border-right-style', 'border-right-color'],
  borderRightColor: ['color', 'transparent'],
  borderRightStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderRightWidth: ['thin', 'medium', 'thick', 'length'],
  borderSpacing: ['length', 'length'],
  borderStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderTop: ['border-top-width', 'border-top-style', 'border-top-color'],
  borderTopColor: ['color', 'transparent'],
  borderTopLeftRadius: ['length', 'percentage'],
  borderTopRightRadius: ['length', 'percentage'],
  borderTopStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderTopWidth: ['thin', 'medium', 'thick', 'length'],
  borderWidth: ['thin', 'medium', 'thick', 'length'],
  bottom: ['auto', 'length', 'percentage'],
  boxShadow: ['none', 'h-shadow v-shadow blur spread color inset', 'h-shadow v-shadow color inset', 'h-shadow v-shadow blur color inset', 'h-shadow v-shadow spread color inset'],
  boxSizing: ['content-box', 'border-box'],
  breakAfter: ['auto', 'avoid', 'avoid-page', 'page', 'left', 'right', 'recto', 'verso', 'avoid-column', 'column', 'avoid-region', 'region'],
  breakBefore: ['auto', 'avoid', 'avoid-page', 'page', 'left', 'right', 'recto', 'verso', 'avoid-column', 'column', 'avoid-region', 'region'],
  breakInside: ['auto', 'avoid', 'avoid-page', 'avoid-column', 'avoid-region'],
  captionSide: ['top', 'bottom', 'block-start', 'block-end', 'inline-start', 'inline-end'],
  caretColor: ['auto', 'color'],
  clear: ['none', 'left', 'right', 'both'],
  clip: ['auto', 'shape', 'rect()'],
  clipPath: ['none', 'url', 'shape', 'inset-rectangle', 'circle', 'ellipse', 'polygon'],
  clipRule: ['nonzero', 'evenodd'],
  color: ['color', 'transparent'],
  columnCount: ['auto', 'number'],
  columnFill: ['auto', 'balance', 'balance-all'],
  columnGap: ['normal', 'length'],
  columnRule: ['column-rule-width', 'column-rule-style', 'column-rule-color'],
  columnRuleColor: ['color', 'transparent'],
  columnRuleStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  columnRuleWidth: ['thin', 'medium', 'thick', 'length'],
  columnSpan: ['none', 'all'],
  columnWidth: ['auto', 'length', 'percentage'],
  columns: ['auto', 'length', 'auto length'],
  content: ['normal', 'none', 'counter', 'attr', 'open-quote', 'close-quote', 'no-open-quote', 'no-close-quote', 'url', 'string', 'counter', 'attr', 'open-quote', 'close-quote', 'no-open-quote', 'no-close-quote', 'url', 'string'],
  counterIncrement: ['none', 'identifier number'],
  counterReset: ['none', 'identifier number'],
  cursor: ['auto', 'default', 'none', 'context-menu', 'help', 'pointer', 'progress', 'wait', 'cell', 'crosshair', 'text', 'vertical-text', 'alias', 'copy', 'move', 'no-drop', 'not-allowed', 'grab', 'grabbing', 'all-scroll', 'col-resize', 'row-resize', 'n-resize', 'e-resize', 's-resize', 'w-resize', 'ne-resize', 'nw-resize', 'se-resize', 'sw-resize', 'ew-resize', 'ns-resize', 'nesw-resize', 'nwse-resize', 'zoom-in', 'zoom-out'],
  direction: ['ltr', 'rtl'],
  display: ['none', 'inline', 'block', 'inline-block', 'flex', 'inline-flex', 'grid', 'inline-grid', 'table', 'inline-table', 'table-row', 'table-cell', 'list-item', 'run-in', 'contents', 'flow', 'flow-root', 'none', 'table-row-group', 'table-header-group', 'table-footer-group', 'table-row', 'table-cell', 'table-column-group', 'table-column', 'table-caption', 'ruby', 'ruby-base', 'ruby-text', 'ruby-base-container', 'ruby-text-container', 'contents', 'none'],
  emptyCells: ['show', 'hide'],
  filter: ['none', 'url', 'blur', 'brightness', 'contrast', 'drop-shadow', 'grayscale', 'hue-rotate', 'invert', 'opacity', 'saturate', 'sepia'],
  flex: ['flex-grow', 'flex-shrink', 'flex-basis'],
  flexBasis: ['auto', 'length', 'percentage', 'content'],
  flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
  flexFlow: ['flex-direction', 'flex-wrap'],
  flexGrow: ['number'],
  flexShrink: ['number'],
  flexWrap: ['nowrap', 'wrap', 'wrap-reverse'],
  float: ['none', 'left', 'right'],
  fontFamily: ['Inter', 'generic-family'],
  fontFeatureSettings: ['normal', 'feature-value'],
  fontKerning: ['auto', 'normal', 'none'],
  fontLanguageOverride: ['normal', 'language-tag'],
  fontSize: ['xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large', 'smaller', 'larger', 'length', 'percentage'],
  fontSizeAdjust: ['none', 'number'],
  fontStretch: ['normal', 'ultra-condensed', 'extra-condensed', 'condensed', 'semi-condensed', 'semi-expanded', 'expanded', 'extra-expanded', 'ultra-expanded'],
  fontStyle: ['normal', 'italic', 'oblique'],
  fontSynthesis: ['none', 'weight', 'style', 'weight style'],
  fontVariant: ['normal', 'small-caps'],
  fontVariantAlternates: ['normal', 'stylistic()'],
  fontVariantCaps: ['normal', 'small-caps', 'all-small-caps', 'petite-caps', 'all-petite-caps', 'unicase', 'titling-caps'],
  fontVariantEastAsian: ['normal', 'jis78', 'jis83', 'jis90', 'jis04', 'simplified', 'traditional'],
  fontVariantLigatures: ['normal', 'none', 'common-ligatures', 'no-common-ligatures', 'discretionary-ligatures', 'no-discretionary-ligatures', 'historical-ligatures', 'no-historical-ligatures', 'contextual', 'no-contextual'],
  fontVariantNumeric: ['normal', 'ordinal', 'slashed-zero', 'lining-nums', 'oldstyle-nums', 'proportional-nums', 'tabular-nums', 'diagonal-fractions', 'stacked-fractions'],
  fontVariantPosition: ['normal', 'sub', 'super'],
  fontWeight: ['normal', 'bold', 'bolder', 'lighter', 'number', '100', '200','300','400','500','600','700','800','900', ],
  gap: ['length', 'percentage'],
  grid: ['grid-template-rows', 'grid-template-columns', 'grid-template-areas', 'grid-auto-rows', 'grid-auto-columns', 'grid-auto-flow'],
  gridArea: ['grid-row-start', 'grid-column-start', 'grid-row-end', 'grid-column-end'],
  gridAutoColumns: ['auto', 'length', 'percentage'],
  gridAutoFlow: ['row', 'column', 'dense', 'row dense', 'column dense'],
  gridAutoRows: ['auto', 'length', 'percentage'],
  gridColumn: ['grid-column-start', 'grid-column-end'],
  gridColumnEnd: ['grid-column-end'],
  gridColumnGap: ['length', 'percentage'],
  gridColumnStart: ['grid-column-start'],
  gridGap: ['length', 'percentage'],
  gridRow: ['grid-row-start', 'grid-row-end'],
  gridRowEnd: ['grid-row-end'],
  gridRowGap: ['length', 'percentage'],
  gridRowStart: ['grid-row-start'],
  gridTemplate: ['grid-template-rows', 'grid-template-columns', 'grid-template-areas'],
  gridTemplateAreas: ['none', 'grid-area-name'],
  gridTemplateColumns: ['none', 'length', 'percentage', 'min-content', 'max-content', 'auto', 'repeat()'],
  gridTemplateRows: ['none', 'length', 'percentage', 'min-content', 'max-content', 'auto', 'repeat()'],
  hangingPunctuation: ['none', 'first', 'last', 'allow-end', 'force-end', 'first last', 'first allow-end', 'first force-end', 'last allow-end', 'last force-end', 'allow-end force-end'],
  height: ['auto', 'length', 'percentage'],
  hyphens: ['none', 'manual', 'auto'],
  imageOrientation: ['auto', 'flip', 'none'],
  imageRendering: ['auto', 'smooth', 'high-quality', 'crisp-edges', 'pixelated'],
  inlineSize: ['auto', 'length', 'percentage'],
  inset: ['auto', 'length', 'percentage'],
  isolation: ['auto', 'isolate'],
  justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly'],
  justifyItems: ['auto', 'normal', 'stretch', 'center', 'start', 'end', 'flex-start', 'flex-end', 'self-start', 'self-end', 'left', 'right', 'baseline', 'first baseline', 'last baseline', 'safe center', 'unsafe center'],
  justifySelf: ['auto', 'normal', 'stretch', 'center', 'start', 'end', 'flex-start', 'flex-end', 'self-start', 'self-end', 'left', 'right', 'baseline', 'first baseline', 'last baseline', 'safe center', 'unsafe center'],
  left: ['auto', 'length', 'percentage'],
  letterSpacing: ['normal', 'length'],
  lineBreak: ['auto', 'loose', 'normal', 'strict', 'anywhere'],
  lineHeight: ['normal', 'number', 'length', 'percentage'],
  listStyle: ['list-style-type', 'list-style-position', 'list-style-image'],
  listStyleImage: ['url', 'none'],
  listStylePosition: ['inside', 'outside'],
  listStyleType: ['none', 'disc', 'circle', 'square', 'decimal', 'decimal-leading-zero', 'lower-roman', 'upper-roman', 'lower-greek', 'lower-latin', 'upper-latin', 'armenian', 'georgian', 'lower-alpha', 'upper-alpha', 'none'],
  margin: ['auto', 'length', 'percentage'],
  marginBlock: ['auto', 'length', 'percentage'],
  marginBlockEnd: ['auto', 'length', 'percentage'],
  marginBlockStart: ['auto', 'length', 'percentage'],
  marginBottom: ['auto', 'length', 'percentage'],
  marginInline: ['auto', 'length', 'percentage'],
  marginInlineEnd: ['auto', 'length', 'percentage'],
  marginInlineStart: ['auto', 'length', 'percentage'],
  marginLeft: ['auto', 'length', 'percentage'],
  marginRight: ['auto', 'length', 'percentage'],
  marginTop: ['auto', 'length', 'percentage'],
  marker: ['none', 'url'],
  markerEnd: ['none', 'url'],
  markerMid: ['none', 'url'],
  markerStart: ['none', 'url'],
  mask: ['mask-image', 'mask-mode', 'mask-repeat', 'mask-position', 'mask-clip', 'mask-origin', 'mask-size', 'mask-composite'],
  maskBorder: ['mask-border-source', 'mask-border-slice', 'mask-border-width', 'mask-border-outset', 'mask-border-repeat'],
  maskBorderMode: ['alpha', 'luminance'],
  maskBorderOutset: ['length', 'number'],
  maskBorderRepeat: ['stretch', 'repeat', 'round', 'space'],
  maskBorderSlice: ['number', 'percentage', 'fill'],
  maskBorderSource: ['none', 'url'],
  maskBorderWidth: ['length', 'percentage'],
  maskClip: ['border-box', 'padding-box', 'content-box', 'text'],
  maskComposite: ['add', 'subtract', 'intersect', 'exclude'],
  maskImage: ['none', 'url'],
  maskMode: ['alpha', 'luminance'],
  maskOrigin: ['border-box', 'padding-box', 'content-box', 'text'],
  maskPosition: ['center', 'top', 'right', 'bottom', 'left', 'x% y%', 'xpos ypos'],
  maskRepeat: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
  maskSize: ['auto', 'cover', 'contain'],
  maxBlockSize: ['none', 'length', 'percentage'],
  maxHeight: ['none', 'length', 'percentage'],
  maxInlineSize: ['none', 'length', 'percentage'],
  maxWidth: ['none', 'length', 'percentage'],
  minBlockSize: ['length', 'percentage'],
  minHeight: ['length', 'percentage'],
  minInlineSize: ['length', 'percentage'],
  minWidth: ['length', 'percentage'],
  mixBlendMode: ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity'],
  objectFit: ['fill', 'contain', 'cover', 'none', 'scale-down'],
  objectPosition: ['center', 'top', 'right', 'bottom', 'left', 'x% y%', 'xpos ypos'],
  offset: ['auto', 'length', 'percentage'],
  offsetAnchor: ['auto', 'length', 'percentage'],
  offsetDistance: ['auto', 'length', 'percentage'],
  offsetPath: ['none', 'path()', 'url'],
  offsetRotate: ['auto', 'angle'],
  opacity: ['number'],
  order: ['number'],
  orphans: ['number'],
  outline: ['outline-color', 'outline-style', 'outline-width'],
  outlineColor: ['color', 'invert'],
  outlineOffset: ['length'],
  outlineStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  outlineWidth: ['thin', 'medium', 'thick', 'length'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'overlay'],
  overflowAnchor: ['auto', 'none'],
  overflowBlock: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'overlay'],
  overflowClipBox: ['padding-box', 'content-box'],
  overflowInline: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'overlay'],
  overflowWrap: ['normal', 'break-word'],
  overflowX: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'overlay'],
  overflowY: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'overlay'],
  overscrollBehavior: ['auto', 'contain', 'none'],
  overscrollBehaviorBlock: ['auto', 'contain', 'none'],
  overscrollBehaviorInline: ['auto', 'contain', 'none'],
  overscrollBehaviorX: ['auto', 'contain', 'none'],
  overscrollBehaviorY: ['auto', 'contain', 'none'],
  padding: ['length', 'percentage'],
  paddingBlock: ['length', 'percentage'],
  paddingBlockEnd: ['length', 'percentage'],
  paddingBlockStart: ['length', 'percentage'],
  paddingBottom: ['length', 'percentage'],
  paddingInline: ['length', 'percentage'],
  paddingInlineEnd: ['length', 'percentage'],
  paddingInlineStart: ['length', 'percentage'],
  paddingLeft: ['length', 'percentage'],
  paddingRight: ['length', 'percentage'],
  paddingTop: ['length', 'percentage'],
  pageBreakAfter: ['auto', 'always', 'avoid', 'left', 'right'],
  pageBreakBefore: ['auto', 'always', 'avoid', 'left', 'right'],
  pageBreakInside: ['auto', 'avoid'],
  paintOrder: ['normal', 'fill', 'stroke', 'markers'],
  perspective: ['none', 'length'],
  perspectiveOrigin: ['length', 'percentage'],
  placeContent: ['normal', 'start', 'end', 'flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'stretch', 'baseline', 
              'first baseline', 'last baseline', 'safe center', 'unsafe center'],
  placeItems: ['normal', 'start', 'end', 'flex-start', 'flex-end', 'center', 'stretch', 'self-start', 'self-end', 'baseline', 
           'first baseline', 'last baseline', 'safe center', 'unsafe center'],
  placeSelf: ['auto', 'normal', 'start', 'end', 'flex-start', 'flex-end', 'center', 'stretch', 'self-start', 'self-end', 'baseline', 
           'first baseline', 'last baseline', 'safe center', 'unsafe center'],
  pointerEvents: ['auto', 'none'],
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
  quotes: ['none', 'string string'],
  resize: ['none', 'both', 'horizontal', 'vertical'],
  right: ['auto', 'length', 'percentage'],
  rotate: ['angle'],
  rowGap: ['normal', 'length'],
  rubyAlign: ['start', 'center', 'space-between', 'space-around'],
  rubyMerge: ['auto', 'collapse', 'separate'],
  rubyPosition: ['over', 'under', 'inter-character'],
  scale: ['number'],
  scrollBehavior: ['auto', 'smooth'],
  scrollMargin: ['auto', 'length'],
  scrollMarginBlock: ['auto', 'length'],
  scrollMarginBlockEnd: ['auto', 'length'],
  scrollMarginBlockStart: ['auto', 'length'],
  scrollMarginBottom: ['auto', 'length'],
  scrollMarginInline: ['auto', 'length'],
  scrollMarginInlineEnd: ['auto', 'length'],
  scrollMarginInlineStart: ['auto', 'length'],
  scrollMarginLeft: ['auto', 'length'],
  scrollMarginRight: ['auto', 'length'],
  scrollMarginTop: ['auto', 'length'],
  scrollPadding: ['auto', 'length'],
  scrollPaddingBlock: ['auto', 'length'],
  scrollPaddingBlockEnd: ['auto', 'length'],
  scrollPaddingBlockStart: ['auto', 'length'],
  scrollPaddingBottom: ['auto', 'length'],
  scrollPaddingInline: ['auto', 'length'],
  scrollPaddingInlineEnd: ['auto', 'length'],
  scrollPaddingInlineStart: ['auto', 'length'],
  scrollPaddingLeft: ['auto', 'length'],
  scrollPaddingRight: ['auto', 'length'],
  scrollPaddingTop: ['auto', 'length'],
  scrollSnapAlign: ['none', 'start', 'end', 'center', 'none start', 'none end', 'none center', 'start none', 'end none', 'center none'],
  scrollSnapStop: ['normal', 'always'],
  scrollSnapType: ['none', 'mandatory', 'proximity'],
  shapeImageThreshold: ['number'],
  shapeMargin: ['length', 'percentage'],
  shapeOutside: ['none', 'shape-box', 'url', 'margin-box', 'content-box', 'border-box', 'padding-box', 'fill-box', 'stroke-box', 'view-box'],
  shapeRendering: ['auto', 'optimizeSpeed', 'crispEdges', 'geometricPrecision'],
  stopColor: ['color', 'currentcolor'],
  stopOpacity: ['number'],
  stroke: ['none', 'color'],
  strokeDasharray: ['none', 'length', 'percentage'],
  strokeDashoffset: ['length', 'percentage'],
  strokeLinecap: ['butt', 'round', 'square'],
  strokeLinejoin: ['miter', 'round', 'bevel'],
  strokeMiterlimit: ['number'],
  strokeOpacity: ['number'],
  strokeWidth: ['length', 'percentage'],
  tabSize: ['number'],
  tableLayout: ['auto', 'fixed'],
  textAlign: ['left', 'right', 'center', 'justify', 'start', 'end', 'match-parent'],
  textAlignLast: ['auto', 'start', 'end', 'left', 'right', 'center', 'justify'],
  textAnchor: ['start', 'middle', 'end'],
  textCombineUpright: ['none', 'all', 'digits', 'digits 2', 'digits 3', 'digits 4', 'digits 5', 'digits 6', 'digits 7', 'digits 8', 
                    'digits 9', 'digits 10', 'digits 11', 'digits 12', 'digits 13', 'digits 14', 'digits 15', 'digits 16',
                    'digits 17', 'digits 18', 'digits 19', 'digits 20', 'digits 21', 'digits 22', 'digits 23',
                    'digits 24', 'digits 25', 'digits 26', 'digits 27', 'digits 28', 'digits 29', 'digits 30',
                    'digits 31', 'digits 32', 'digits 33', 'digits 34', 'digits 35', 'digits 36'],
  textDecoration: ['none', 'underline', 'overline', 'line-through', 'blink'],
  textDecorationColor: ['color', 'currentcolor'],
  textDecorationLine: ['none', 'underline', 'overline', 'line-through'],
  textDecorationSkip: ['none', 'objects', 'spaces', 'ink', 'edges', 'box-decoration', 'objects spaces', 
                    'objects ink', 'objects edges', 'objects box-decoration', 'spaces ink', 'spaces edges',
                    'spaces box-decoration', 'ink edges', 'ink box-decoration', 'edges box-decoration',
                    'objects spaces ink', 'objects spaces edges', 'objects spaces box-decoration',
                    'objects ink edges', 'objects ink box-decoration', 'objects edges box-decoration',
                    'spaces ink edges', 'spaces ink box-decoration', 'spaces edges box-decoration',
                    'ink edges box-decoration', 'objects spaces ink edges',
                    'objects spaces ink box-decoration', 'objects spaces edges box-decoration',
                    'objects ink edges box-decoration', 'spaces ink edges box-decoration',
                    'objects spaces ink edges box-decoration'],
  textDecorationStyle: ['solid', 'double', 'dotted', 'dashed', 'wavy'],
  textEmphasis: ['none', 'string', 'color', 'filled', 'open'],
  textEmphasisColor: ['color', 'currentcolor'],
  textEmphasisPosition: ['over', 'under'],
  textEmphasisStyle: ['none', 'filled', 'open', 'dot', 'circle', 'double-circle', 
                    'triangle', 'sesame', 'string'],
  textIndent: ['length', 'percentage'],
  textJustify: ['auto', 'inter-word', 'inter-character', 'none'],
  textOrientation: ['mixed', 'upright', 'sideways', 'sideways-right', 'sideways-left', 
                 'use-glyph-orientation'],
  textOverflow: ['clip', 'ellipsis'],
  textRendering: ['auto', 'optimizeSpeed', 'optimizeLegibility', 'geometricPrecision'],
  textShadow: ['none', 'h-shadow v-shadow blur color', 'h-shadow v-shadow color', 
           'h-shadow v-shadow blur', 'h-shadow v-shadow'],
  textTransform: ['none', 'capitalize', 'uppercase', 'lowercase', 'full-width', 
              'full-size-kana'],
  textUnderlineOffset: ['auto', 'length'],
  textUnderlinePosition: ['auto', 'under', 'left', 'right'],
  top: ['auto', 'length', 'percentage'],
  touchAction: ['auto', 'none', 'pan-x', 'pan-left', 'pan-right', 'pan-y', 
              'pan-up', 'pan-down', 'pinch-zoom', 'manipulation'],
  transform: ['none', 'matrix()', 'matrix3d()', 'translate()', 'translate3d()', 
           'translateX()', 'translateY()', 'translateZ()', 'scale()', 
           'scale3d()', 'scaleX()', 'scaleY()', 'scaleZ()', 
           'rotate()', 'rotate3d()', 'rotateX()', 'rotateY()', 
           'rotateZ()', 'skew()', 'skewX()', 'skewY()', 
           'perspective()'],
  transformBox: ['border-box', 'fill-box', 'view-box'],
  transformOrigin: ['length', 'percentage', 'left', 'center', 
                 'right', 'top', 'bottom'],
                 transformStyle: ['flat', 'preserve-3d'],
  transition: ['transition-property', 'transition-duration', 'transition-timing-function', 'transition-delay'],
  transitionDelay: ['time'],
  transitionDuration: ['time'],
  transitionProperty: ['none', 'all', 'property'],
  transitionTimingFunction: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out', 'step-start', 'step-end', 'steps()', 'cubic-bezier()'],
  translate: ['length', 'percentage'],
  unicodeBidi: ['normal', 'embed', 'isolate', 'bidi-override', 'isolate-override', 'plaintext'],
  userSelect: ['auto', 'none', 'text', 'contain', 'all'],
  verticalAlign: ['baseline', 'sub', 'super', 'text-top', 'text-bottom', 'middle', 'top', 'bottom', 'length', 'percentage'],
  visibility: ['visible', 'hidden', 'collapse'],
  whiteSpace: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line'],
  widows: ['number'],
  width: ['auto', 'length', 'percentage'],
  willChange: ['auto', 'scroll-position', 'contents', 'transform', 'opacity', 'left', 'top', 'right', 
              'bottom', 'width', 'height', 'margin', 'padding', 'border', 'color', 
              'background', 'font', 'line-height', 'visibility','overflow','clip','float',
              'clear','cursor','pointer-events','z-index','box-shadow','text-shadow',
              'perspective','perspective-origin','transform-style','backface-visibility',
              'animation','transition'],
  wordBreak: ['normal', 'break-all', 'keep-all', 'break-word'],
  wordSpacing: ['normal', 'length'],
  wordWrap: ['normal', 'break-word'],
  writingMode: ['horizontal-tb', 'vertical-rl', 'vertical-lr', 'sideways-rl', 'sideways-lr'],
  zIndex: ['auto', 'number'],
  zoom: ['normal', 'reset', 'reset-inherit', 'inherit', 'number'],
};